//
//  LoginPagePresenter.swift
//  Movee
//
//  Created by Oguz Tandogan on 6.12.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class LoginPagePresenter {

    // MARK: - Private properties -

    private unowned let view: LoginPageViewInterface
    private let formatter: LoginPageFormatterInterface
    private let interactor: LoginPageInteractorInterface
    private let wireframe: LoginPageWireframeInterface

    // MARK: - Lifecycle -

    init(view: LoginPageViewInterface, formatter: LoginPageFormatterInterface, interactor: LoginPageInteractorInterface, wireframe: LoginPageWireframeInterface) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension LoginPagePresenter: LoginPagePresenterInterface {
    
    func viewDidLoad() {
    }
    
    func loadLoginData(username: String?, password: String?) {
        interactor.authenticateWithUserCredentials(username: username, password: password)
    }
}
