//
//  LoginPagePresenter.swift
//  Movee
//
//  Created by Oguz Tandogan on 6.12.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import MoveeComponents
import Utilities
import MoveeWebService

final class LoginPagePresenter {

    // MARK: - Private properties -

    private unowned let view: LoginPageViewInterface
    private let formatter: LoginPageFormatterInterface
    private let interactor: LoginPageInteractorInterface
    private let wireframe: LoginPageWireframeInterface

    private let loginCallback = LoginCallback()
    // MARK: - Lifecycle -

    init(view: LoginPageViewInterface, formatter: LoginPageFormatterInterface, interactor: LoginPageInteractorInterface, wireframe: LoginPageWireframeInterface) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
    }
    
    private func getLoginSessionId() {
        loginCallback.commonResult { [weak self] (result) in
            self?.handleLoginResponse(result: result)
        }
        interactor.getAuthenticatedSessionId(callback: loginCallback, params: LoginRequestModel())
    }
    private func handleLoginResponse(result: Result<LoginResponseModel, BaseErrorResponse>) {
        switch result {
        case .failure(let error):
            print(error)
        case .success(let success):
            print(success)
        }
    }
}

// MARK: - Extensions -

extension LoginPagePresenter: LoginPagePresenterInterface {
    
    func viewDidLoad() {
        getLoginSessionId()
    }
    
    func loadLoginData(username: String?, password: String?) {
//        interactor.authenticateWithUserCredentials(username: username, password: password)
    }
}
