//
//  LoginPageInteractor.swift
//  Movee
//
//  Created by Oguz Tandogan on 6.12.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class LoginPageInteractor {
}

// MARK: - Extensions -

extension LoginPageInteractor: LoginPageInteractorInterface {
    
    func authenticateWithUserCredentials(username: String?, password: String?) {
        TmDBService.instance.getToken(completion: {response in
            let loginRequestModel = LoginRequestModel(username: response.request_token,
                                                      password: password,
                                                      request_token: username)
//            self.loginRequestModel?.request_token = response.request_token
//            self.loginRequestModel?.password = password
//            self.loginRequestModel?.username = username
            print("asdfasdfa")
            TmDBService.instance.createSessionWithLogin(requestModel: loginRequestModel, completion: { requestToken, response1  in
                guard let isSuccess = response1?.success else {
                    fatalError("error")
                }
                if isSuccess {
                    TmDBService.instance.createSessionID(requestModel: response1?.request_token, completion: { savedToken, sessionId in
                        guard let isSuccess = response1?.success else {
                            fatalError("error")
                        }
                        if isSuccess {
                            TmDBService.instance.getAccountDetails(requestModel: sessionId.session_id, completion: { accountDetails in
                                DispatchQueue.main.async {
                                    if let accountId = accountDetails.id {
                                        let accountIdString = String(accountId)
                                        UserDefaults.standard.set(accountIdString, forKey: "AccountId")
                                        if accountIdString != nil {
                                            UserDefaults.standard.set(true, forKey: "IsLoggedIn")
                                        }
                                    }
                                }
                            })
                        } else {
                            fatalError("error")
                        }
                    })
                    
                } else {
                    fatalError("error")
                }
                
            })
        })
        
    }
}
