//
//  LoginPageInteractor.swift
//  Movee
//
//  Created by Oguz Tandogan on 6.12.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class LoginPageInteractor {
    let loginRequestModel: LoginRequestModel? = nil
}

// MARK: - Extensions -

extension LoginPageInteractor: LoginPageInteractorInterface {
    
    func authenticateWithUserCredentials(username: String?, password: String?) {
        TmDBService.instance.getToken(completion: {response in
            self.loginRequestModel?.request_token = response.request_token
            self.loginRequestModel?.password = password
            self.loginRequestModel?.username = username
            
            TmDBService.instance.createSessionWithLogin(requestModel: self.loginRequestModel, completion: { requestToken, response  in
                guard let isSuccess = response?.success else {
                    fatalError("error")
                }
                if isSuccess {
                    TmDBService.instance.createSessionID(requestModel: response?.request_token, completion: { savedToken, sessionId in
                        if let isSuccess = sessionId.success, isSuccess {
                            TmDBService.instance.getAccountDetails(requestModel: sessionId.session_id, completion: { accountDetails in
                                DispatchQueue.main.async {
                                    if let accountId = accountDetails.id {
                                        let accountIdString = String(accountId)
                                        UserDefaults.standard.set(accountIdString, forKey: "AccountId")
                                        if accountIdString != nil {
                                            UserDefaults.standard.set(true, forKey: "IsLoggedIn")
                                        }
                                    }
                                }
                            })
                        }
                    })
                    
                } else {
                    fatalError("error")
                }
                
            })
        })
        
    }
}
