//
//  LoginPageFormatter.swift
//  Movee
//
//  Created by Oguz Tandogan on 6.12.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginPageFormatter {
}

// MARK: - Extensions -

extension LoginPageFormatter: LoginPageFormatterInterface {
}
