//
//  LoginViewController.swift
//  Movee
//
//  Created by Hazal Eroglu on 17.11.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import MoveeComponents

final class LoginViewController: UIViewController {

    private var loginPageComponent: LoginPageComponent!
    
    // MARK: - Public properties -

    var presenter: LoginPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        loginPageComponent.listenLoginButtonAction { [weak self] (data) in
            self?.presenter.fireAuthenticationFlow(authentication: data)
        }
    }

}

// MARK: - Extensions -

extension LoginViewController: LoginViewInterface {
}
