//
//  LoginFormatter.swift
//  Movee
//
//  Created by Hazal Eroglu on 17.11.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginFormatter {
}

// MARK: - Extensions -

extension LoginFormatter: LoginFormatterInterface {
}


