//
//  LoginInteractor.swift
//  Movee
//
//  Created by Hazal Eroglu on 17.11.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

final class LoginInteractor {

}

// MARK: - Extensions -

extension LoginInteractor: LoginInteractorInterface {
    
    
    func getApiResponse() {
        
        TmDBService.instance.getToken(completion: {response in
            TmDBService.instance.token = response.request_token
        })
    }
    
    func getAccess(requestModel: LoginRequestModel?) {
        TmDBService.instance.createSessionWithLogin(requestModel: requestModel, completion: { requestToken, response  in
            if let isSuccess = response?.success, isSuccess {
                UserDefaults.standard.set(response?.request_token, forKey: "SavedToken")
            } else {
                fatalError("error")
            }
            if response?.success == true {
                self.getSessionId(requestModel: response?.request_token)
            }
        })
    }
    
    func getSessionId(requestModel: String?) {
        TmDBService.instance.createSessionID(requestModel: requestModel,
                                             completion: { savedToken, sessionId in
            if let isSuccess = sessionId.success, isSuccess {
                self.getAccountDetails(requestModel: sessionId.session_id)
            }
        })
    }
    
    func getAccountDetails(requestModel: String?) {
        TmDBService.instance.getAccountDetails(requestModel: requestModel, completion: { accountDetails in
            DispatchQueue.main.async {
                if let accountId = accountDetails.id {
                    let accountIdString = String(accountId)
                    UserDefaults.standard.set(accountIdString, forKey: "AccountId")
                    if accountIdString != nil {
                        UserDefaults.standard.set(true, forKey: "IsLoggedIn")
                    }
                }
            }
        })
    }
}
