//
//  LoginPageInteractor.swift
//  Movee
//
//  Created by Oguz Tandogan on 6.12.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import MoveeWebService

final class LoginInteractor: AssemblerWireframeInteractorProtocol {
    
    private var usecase: SessionUsecase?
}

// MARK: - Extensions -

extension LoginInteractor: LoginInteractorInterface {
    
    func getSessionId(callback: LoginCallback, params: LoginRequestModel) {
        usecase = returnResolver().resolve(SessionUsecase.self)
        usecase?.execute(useCaseCallBack: callback, params: params)
    }
}
