//
//  LoginPresenter.swift
//  Movee
//
//  Created by Hazal Eroglu on 17.11.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//


import Foundation
import Utilities
import MoveeComponents

final class LoginPresenter {

    // MARK: - Private properties -

    private unowned let view: LoginViewInterface
    private let formatter: LoginFormatterInterface
    private let interactor: LoginInteractorInterface
    private let wireframe: LoginWireframeInterface

    // MARK: - Lifecycle -

    init(view: LoginViewInterface, formatter: LoginFormatterInterface, interactor: LoginInteractorInterface, wireframe: LoginWireframeInterface) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension LoginPresenter: LoginPresenterInterface {
    func fireAuthenticationFlow(authentication: AuthenticationRequest) {
        
    }
    
    
    func viewDidLoad() {
//        loadLoginData()
    }
    
//    func loadLoginData() {
//        interactor.createSessionWithLogin(username: "adsfasdfad", password: "asdfasdfas", request_token: <#T##String?#>, completion: <#T##([String : Any], (SessionWithLoginModel?)) -> Void#>)
//    }
}
