//
//  LoginInterfaces.swift
//  Movee
//
//  Created by Hazal Eroglu on 17.11.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import MoveeComponents
import MoveeWebService

protocol LoginWireframeInterface: WireframeInterface {
}

protocol LoginViewInterface: ViewInterface {
}

protocol LoginPresenterInterface: PresenterInterface {
    func fireAuthenticationFlow(authentication: AuthenticationRequest)
}

protocol LoginFormatterInterface: FormatterInterface {
}

protocol LoginInteractorInterface: InteractorInterface {
    func getSessionId(callback: LoginCallback, params: LoginRequestModel)
}
