//
//  MoviesInteractor.swift
//  Movee
//
//  Created by Hazal Eroglu on 23.12.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import MoveeWebService

final class MoviesInteractor: AssemblerWireframeInteractorProtocol {
    
    private var nowPlayingMoviesUsecase: NowPlayingMoviesUsecase?
    private var popularMoviesUsecase: PopularMoviesUsecase?
}

// MARK: - Extensions -

extension MoviesInteractor: MoviesInteractorInterface {
    
    func fetchPopularMovies(callback: PopularMoviesCallback, params: MoviesRequestModel) {
        popularMoviesUsecase = returnResolver().resolve(PopularMoviesUsecase.self)
        popularMoviesUsecase?.execute(useCaseCallBack: callback, params: params)
    }
    
    func fetchNowPlayingMovies(callback: NowPlayingMoviesCallback, params: MoviesRequestModel) {
        nowPlayingMoviesUsecase = returnResolver().resolve(NowPlayingMoviesUsecase.self)
        nowPlayingMoviesUsecase?.execute(useCaseCallBack: callback, params: params)
    }
    
}
