//
//  MoviesFormatter.swift
//  Movee
//
//  Created by Hazal Eroglu on 23.12.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MoviesFormatter {
}

// MARK: - Extensions -

extension MoviesFormatter: MoviesFormatterInterface {
}
