//
//  MoviesViewController.swift
//  Movee
//
//  Created by Hazal Eroglu on 23.12.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import MoveeComponents

final class MoviesViewController: UIViewController {
    
    // MARK: - Outlets -
    

    // MARK: - Public properties -

    var presenter: MoviesPresenterInterface!
    
    // MARK: - Private Properties -
    
    private var tableView = TableViewComponent()
    private var popularMoviesComponent = PopularMoviesCardComponent()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupNavController()
        presenter.viewDidLoad()
    }

    private func setupNavController() {
        navigationController?.navigationBar.isTranslucent = true
        navigationController?.navigationBar.setBackgroundImage(UIImage(), for: .default)
        navigationController?.navigationBar.shadowImage = UIImage()
    }
    
}

// MARK: - Extensions -

extension MoviesViewController: MoviesViewInterface {
}
