//
//  MoviesInteractor.swift
//  Movee
//
//  Created by Hazal Eroglu on 23.12.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MoviesInteractor {
}

// MARK: - Extensions -

extension MoviesInteractor: MoviesInteractorInterface {
}
