//
//  MoviesInterfaces.swift
//  Movee
//
//  Created by Hazal Eroglu on 23.12.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MoviesWireframeInterface: WireframeInterface {
}

protocol MoviesViewInterface: ViewInterface {
}

protocol MoviesPresenterInterface: PresenterInterface {
}

protocol MoviesFormatterInterface: FormatterInterface {
}

protocol MoviesInteractorInterface: InteractorInterface {
}
