//
//  MoviesPresenter.swift
//  Movee
//
//  Created by Hazal Eroglu on 23.12.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MoviesPresenter {

    // MARK: - Private properties -

    private unowned let view: MoviesViewInterface
    private let formatter: MoviesFormatterInterface
    private let interactor: MoviesInteractorInterface
    private let wireframe: MoviesWireframeInterface

    // MARK: - Lifecycle -

    init(view: MoviesViewInterface, formatter: MoviesFormatterInterface, interactor: MoviesInteractorInterface, wireframe: MoviesWireframeInterface) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension MoviesPresenter: MoviesPresenterInterface {
}
