//
//  SplashScreenFormatter.swift
//  Movee
//
//  Created by Oguz Tandogan on 14.12.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SplashScreenFormatter {
}

// MARK: - Extensions -

extension SplashScreenFormatter: SplashScreenFormatterInterface {
}
