//
//  SplashScreenInterfaces.swift
//  Movee
//
//  Created by Oguz Tandogan on 14.12.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import MoveeWebService

enum SplashScreenNavigationOption {
    case login
}

protocol SplashScreenWireframeInterface: WireframeInterface {
    func navigate(option: SplashScreenNavigationOption)
}

protocol SplashScreenViewInterface: ViewInterface {
}

protocol SplashScreenPresenterInterface: PresenterInterface {
    func getBasicToken()
}

protocol SplashScreenFormatterInterface: FormatterInterface {
}

protocol SplashScreenInteractorInterface: InteractorInterface {
    func getBasicToken(callback: BasicTokenCallback, params: BasicTokenRequestModel)
}
